'''

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.


Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
Example 3:

Input: s = "a", t = "aa"
Output: "a"
Example 4:

Input: s = "ae", t = "aea"
Output: "a"

'''


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        
        
        for char in s:
            
            #We can also pass a third parameter in replace() 
            #function to specify the number of times replacement should be performed.
            #It was passed for test case of when s = a and t =aa
            #If we dont provide the third argument, then the output for the test case
            #would be an empty string
            #which is not true
            #Output shoud be 'a'
            #so for this reason a third argument is provided to replace
            
            t = t.replace(char,"",1)
            
        return t
            
            
        